merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bands/", views.band_list, name="band-list"),
    path("bands/<int:id>/", views.band_detail, name="band-detail"),
    path("bands/add/", views.band_create, name="band-create"),
    path("bands/<int:id>/update/", views.bands_update, name="band-update"),
    path("bands/<int:id>/delete/", views.bands_delete, name="band-delete"),
    path("about-us/", views.about, name="about"),
    path("listings/", views.listings_list, name="listing-list"),
    path("listings/<int:id>", views.listings_detail, name="listing-detail"),
    path("listings/add/", views.Create_new_listing, name="Create-new-listing"),
    path("contact-us/", views.contact, name="contact"),
    path("listings/<int:id>/update", views.listings_update, name="listing-update"),
    path("listings/<int:id>/delete", views.listings_delete, name="listing-delete"),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Band(models.Model):
    def __str__(self) -> str:
        return f"{self.name}"

    class Genre(models.TextChoices):
        HIP_HOP = "HH"
        SYNTH_POP = "SP"
        ALTERNATIVE_ROCK = "AR"
        RNB = "RNB"
        RAP_FR = "R-FR"

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2025)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)


class Listing(models.Model):
    class Type(models.TextChoices):
        Records = "Re"
        Clothing = "Cl"
        Posters = "Po"
        Miscellaneous = "Mi"

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1990), MaxValueValidator(2025)], null=True
    )
    type = models.fields.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms

from listings.models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = "__all__"


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = "__all__"

merchex/listings/views.py
from django.shortcuts import render
from listings.models import Band, Listing
from django.core.mail import send_mail
from django.shortcuts import redirect
from listings.forms import BandForm, ContactUsForm, ListingForm


def band_list(request):
    bands = Band.objects.all()
    return render(request, "listings/band_list.html", {"bands": bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request, "listings/band_detail.html", {"band": band})


def band_create(request):
    if request.method == "POST":
        form = BandForm(request.POST)
        if form.is_valid():
            # crée une nouvelle band et la sauvegarder dans la BD
            band = form.save()
            """
                redirige vers la page de detail du groupe que
                nous venons de creer.
                Nous pouvons fournir les arguments du motif url
                comme arguments à la fonction de redirection
            """
            return redirect("band-detail", band.id)
    else:
        form = BandForm()

    return render(request, "listings/band_create.html", {"form": form})


def bands_update(request, id):
    # On recupère l'objet correspondand à l'ID
    band = Band.objects.get(id=id)

    if request.method == "POST":
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            band = form.save()
            # redirection
            return redirect("band-detail", band.id)
    else:
        # On creer  un formulaire dejà rempli avec l'objet recuperer
        form = BandForm(instance=band)
    # on retourne le rendu
    return render(request, "listings/bands_update.html", {"form": form})


def bands_delete(request, id):
    band = Band.objects.get(id=id)

    if request.method == "POST":
        # supprimer le groupe de la base de données
        band.delete()
        # redirection vers la liste de groupe pour confirmation de la suppression
        return redirect("band-list")
    return render(request, "listings/bands_delete.html", {"band": band})


def about(request):
    return render(request, "listings/about.html")


def listings_list(request):
    listings = Listing.objects.all()
    return render(request, "listings/listings_list.html", {"listings": listings})


def listings_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, "listings/listings_detail.html", {"listing": listing})


def Create_new_listing(request):
    # Si la methode de la requete est POST :
    if request.method == "POST":
        # On crer un formulaire remplie avec les valeures précedemment remplies
        form = ListingForm(request.POST)

        # Si le formulaire est valid :
        if form.is_valid():
            # On enregistre les données dans notre base de donnée
            listing = form.save()

            # on redirige vers une nouvelle page ici la page listing-detail
            return redirect("listing-detail", listing.id)
    # Sinon la methode de la requete est GET
    else:
        # On creer un formulaire vide
        form = ListingForm()

        # On retourne la page Create_new_listing
        return render(request, "listings/Create_new_listing.html", {"form": form})


def listings_update(request, id):
    # On recupère l'objet correspondand à l'ID
    listing = Listing.objects.get(id=id)

    if request.method == "POST":
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # redirection
            return redirect("listing-detail", listing.id)
    else:
        # On creer  un formulaire dejà rempli avec l'objet recuperer
        form = ListingForm(instance=listing)
    # on retourne le rendu
    return render(request, "listings/listings_update.html", {"form": form})


def listings_delete(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == "POST":
        # supprimer le groupe de la base de données
        listing.delete()
        # redirection vers la liste de groupe pour confirmation de la suppression
        return redirect("listing-list")
    return render(request, "listings/listings_delete.html", {"listing": listing})


def contact(request):
    if request.method == "POST":
        # crées une instance de notre formulaire et le remplir avec des données POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f"Message from {form.cleaned_data['name'] or 'anonyme'} via Merchex Contact Us Form",
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data["email"],
                recipient_list=["admin@merchex.xyz"],
            )
            return redirect("contact")

    else:
        # ceci doit etre une requete get donc crée un formulaire vide
        form = ContactUsForm()  # ajout d'un nouveau formulaire

    return render(
        request, "listings/contact.html", {"form": form}
    )  # passe ce formulaire au gabarit

merchex/listings/templates/listings/Create_new_listing.html
{% extends "listings/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Creez une nouvelle annonce</h1>

    <form method='post' action='' class="card p-4 shadow">
        {% csrf_token %}
        {{ form|crispy }}
        <input type='submit' value='Envoyer' class="btn-primary mt-3">
    </form>
{% endblock  %}

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>About Merchex</h1>
    <p>{% lorem 1 b random %}</p>
{% endblock  %}
    

merchex/listings/templates/listings/band_create.html
{% extends "listings/base.html" %}

{% block content %}

    <h1>Créer un nouveau groupe </h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <input type='submit' value='envoyer'>
    </form>

{% endblock  %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html'%}


{% block content %}
    <h2>{{ band.name }}</h2>

    <ul>
        <li>Genre : {{ band.get_genre_display }}</li>
        <li>Année de formation : {{ band.year_formed }}</li>
        <li>Actif : {{ band.active|yesno }}</li>

        {% if band.official_homepage %}
          <li>
            <a href="{{ band.official_homepage }}">
                {{ band.official_homepage }}
            </a>
          </li>
        {% endif %}
    </ul>

    <p> {{band.biography}} </p>

    <h3>Nos annonces :</h3>
    <br>
    <ul>
      {% for listing in band.listing_set.all %}
        <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
      {% empty %}
        <li>Aucune annonce pour ce groupe.</li>
      {% endfor %}
    </ul>

    <hr>
    <br>
    <a href="{% url 'band-list' %}">Retour à tous les groupes</a>
    <a href="{% url 'band-update' band.id %}">Modifier le groupe</a>
    <a href="{% url 'band-delete' band.id %}">Supprimer le groupe</a>

   {% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Groupes</h1>
<a href="{% url 'band-create' %}"><li>Creez un groupe</li></a> <br><br>
<ul>
    {% for band in bands %}
        <li>
            <a href="{% url 'band-detail' band.id %}">{{ band.name|capfirst }}</a>
            - <a href="{% url 'band-update' band.id %}">[Editer]</a>
            - <a href="{% url 'band-delete' band.id %}">[Supprimer]</a>

        </li><br>
    {% endfor %}
</ul>

{% endblock  %}

merchex/listings/templates/listings/bands_update.html
{% extends "listings/base.html" %}

{% block content %}

    <h1>Mettre à jour un  groupe </h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <input type='submit' value='envoyer'>
    </form>

{% endblock  %}

merchex/listings/templates/listings/base.html
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Merchex</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
            <div class="container-fluid">
                <a class='navbar-brand' href="{% url 'band-list' %}"> Merchex</a>
                <div class="navbar-nav ">
                    <a class='navbar-link ml-4' href="{% url 'listing-list' %}"> Annonces</a>
                    <a class='navbar-link ' href="{% url 'band-list' %}"> Groupes</a>
                    <a class='navbar-link' href="{% url 'about' %}"> À Propos de nous</a>
                    <a class='navbar-link' href="{% url 'contact' %}"> Contactez-Nous</a>
                </div>
            </div>
        </nav>

        <div class="container">
            {% block content %}

            {% endblock  %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2>Contactez Nous !</h2>
    <p>"Nous sommes là pour vous aider."</p>
    <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Envoyez' >
    </form>
{% endblock  %}

merchex/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}


{% block content %}   
    
<h1>Hello Django !</h1>
<p>Mes groupes préférés sont : </p>
<ul>
    {% for band in bands %}
        <li>{{ band.name|upper }}</li>    
    {% endfor %}  
</ul>

{% endblock  %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Mes listes</h1>
    <p>Mes groupes préférés sont : </p>
    <ul>
        {% for listing in listings %}
            <li>{{ listing.title|upper }}</li>    
        {% endfor %}  
    </ul>
{% endblock  %}
    

   

merchex/listings/templates/listings/listings_delete.html
{% extends "listings/base.html" %}

{% block content %}

    <h1>Supprimer l'annonce </h1>

    <p> Etes-Vous sûrs de vouloir supprimer l'annonce : {{ listing.title }} ??? </p>

    <form action="" method="post">
        {% csrf_token %}
        <input type='submit' value='Supprimer'>
    </form>

{% endblock  %}

merchex/listings/templates/listings/listings_detail.html
{% extends "listings/base.html" %}

{% block content %}
    <h2>{{ listings.title }}</h2>

    <ul>
        <li>Types : {{ listing.get_type_display }}</li>
        <li>Année : {{ listing.year }}</li>
        <li>Vendu : {{ listing.sold|yesno }}</li>
    </ul>

    <p> {{listing.description}} </p>

    <a href="{% url 'listing-list' %}">Retour à toute les Annonces</a>
    <a href="{% url 'listing-update' listing.id %}">Mettre à jour une annonce</a>
    <a href="{% url 'listing-delete' listing.id %}">Supprimer  une annonce</a>

{% endblock  %}

merchex/listings/templates/listings/listings_list.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Annonces</h1>
     <a href="{% url 'Create-new-listing' %}"><li>Creez une annonce</li></a> <br><br>

    <ul>
        {% for listing in listings %}
        <li>
            <a href="{% url 'listing-detail' listing.id  %}">{{ listing.title|upper }}</a>
            - <a href="{% url 'listing-update' listing.id  %}"> [modifier] </a>
            - <a href="{% url 'listing-delete' listing.id  %}"> [Supprimer] </a>

        </li>
        {% endfor %}
    </ul>
{% endblock  %}

merchex/listings/templates/listings/listings_update.html
{% extends "listings/base.html" %}

{% block content %}

    <h1>Mettre à jour une annonce </h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <input type='submit' value='envoyer'>
    </form>

{% endblock  %}